require 'minitest/autorun'

require_relative '../lib/table'
require_relative '../lib/position'
require_relative '../lib/robot'
require_relative '../lib/robot_error'
require_relative '../lib/commands/place'
require_relative '../lib/commands/left'
require_relative '../lib/commands/right'
require_relative '../lib/commands/report'
require_relative '../lib/commands/move'
require_relative '../lib/commands/bad'
require_relative '../lib/simulator'
